import torch
import os


STANZA_RESOURCES_DIR = os.getenv('STANZA_RESOURCES_DIR')

model = torch.load(os.path.join(STANZA_RESOURCES_DIR, 'de/lemma/gsd_charlm.pt'), map_location='cpu')
word_dict, composite_dict = model['dicts']

word_dict['mohren'] = word_dict['mohrchen'] = 'mohr'
word_dict['negeren'] = 'neger'
word_dict['negerinnen'] = 'negerin'
word_dict['gastarbeitern'] = 'gastarbeiter'
word_dict['schwarzafrikas'] = 'schwarzafrika'
word_dict['liliputaners'] = 'liliputaner'
word_dict['zwergen'] = word_dict['zwerge'] = 'zwerg'
word_dict['zwerginnen'] = 'zwergin'
word_dict['südländers'] = word_dict['südländern'] = 'südländer'
word_dict['abendländischen'] = word_dict['abendländisch'] = 'abendland'
word_dict['arbeiter'] = word_dict['arbeitern'] = 'arbeit'
word_dict['muselmänner'] = 'muselmann'
word_dict['chinesische'] = 'chinese'
word_dict['häuptlings'] = 'häuptling'
word_dict['negroiden'] = 'negroid'
word_dict['slawen'] = 'slawe'
word_dict['slawinern'] = 'slawin'
word_dict['türkinnen'] = 'türkin'
word_dict['türken'] = 'türke'
word_dict['verjudete'] = 'verjudet'
word_dict['national'] = 'nation'
word_dict['schauen'] = word_dict['schaue'] = 'schau'
word_dict['nutten'] = 'nutte'
word_dict['halbblüte'] = 'halbblut'
word_dict['mauscheleien'] = 'mauschelei'
word_dict['kontinents'] = 'kontinent'
word_dict['judenschulen'] = 'judenschule'
word_dict['brunnenvergiftern'] = 'brunnenvergifter'
word_dict['behinderte'] = word_dict['behinderten'] = 'behinderte'
word_dict['barbaren'] = 'barbar'
word_dict['pygmäinnen'] = 'pygmäin'
word_dict['indianerin'] = 'indianerin'
word_dict['taubstummer'] = 'taubstumm'
word_dict['halbjuden'] = 'halbjude'
word_dict['mischehen'] = 'mischehe'
word_dict['mestizinnen'] = 'mestizin'
word_dict['kanaken'] = 'kanake'
word_dict['geschachert'] = word_dict['geschacher'] = 'geschach'
word_dict['kaffern'] = 'kaffer'
word_dict['invaliden'] = 'invalide'
word_dict['mischlinge'] = 'mischling'
word_dict['maroons'] = 'maroon'
word_dict['marone'] = 'maron'
word_dict['sodomiten'] = 'sodomit'
word_dict['sklaven'] = 'sklave'
word_dict['mongoloiden'] = 'mongoloid'
word_dict['eingeboren'] = 'eingebore'
word_dict['schauen'] = word_dict['schaue'] = 'schau'
word_dict['kontinents'] = 'kontinent'
word_dict['länders'] = 'land'
word_dict['nachweisen'] = word_dict['nachweises'] = 'nachweis'

torch.save(model, os.path.join(STANZA_RESOURCES_DIR, 'de/lemma/gsd_charlm_customized.pt'))
